### ISSUE TITLE
passwd directory files don't work

### ISSUE THREAD

**Issue by famesjranko** [k44sh/rutorrent#2]
auth passwords not working as expected.

I checked the nginx conf files in the container and found that "auth_basic and  auth_basic_user_file were both unset and commented out within each respective file for rpc, webdav, rutorrent.

To fix, I simply uncommented and set the auth_basic_user_file to the correct file within /passwd

Example for /etc/nginx/conf.d/rutorrent.conf
```    
auth_basic "Restricted Access";
auth_basic_user_file /passwd/rutorrent.htpasswd;
```

**Comment by k44sh** [comment]
Hi,

Have you setup `htpasswd` before ? 

https://github.com/k44sh/rutorrent/blob/main/rootfs/etc/cont-init.d/configurations.sh#L188
Doc: https://github.com/k44sh/rutorrent/blob/main/README.md?plain=1#L195

If it is commented it is because at the time of the initialization of the container there was no `htpasswd`

**Comment by famesjranko** [comment]
oh interesting... Yes I have used htpasswd many times, but wasn't aware that's how your container was designed to build on init.

Thanks for clarifying that.  It was an easy fix on my part for how I set it up, so no big problem either way.  Good to know for next time though. Thanks

BTW I really like the choices you made for this build; is it a fork of crazy-max's?  Having /config instead of /data made it much easier to integrate with sonarr/radarr.
